"""initial_schema

Revision ID: a4d7c2e3b56f
Revises: 
Create Date: 2026-09-25 03:03:23.032304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4d7c2e3b56f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audiobooks',
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_image_url', sa.String(length=1024), nullable=True),
    sa.Column('source_file_url', sa.String(length=1024), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('visibility', sa.Enum('PUBLIC', 'PRIVATE', name='audiobookvisibility', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='audiobookstatus', native_enum=False), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audiobooks_author'), 'audiobooks', ['author'], unique=False)
    op.create_index(op.f('ix_audiobooks_id'), 'audiobooks', ['id'], unique=False)
    op.create_index(op.f('ix_audiobooks_language'), 'audiobooks', ['language'], unique=False)
    op.create_index(op.f('ix_audiobooks_owner_id'), 'audiobooks', ['owner_id'], unique=False)
    op.create_index(op.f('ix_audiobooks_status'), 'audiobooks', ['status'], unique=False)
    op.create_index(op.f('ix_audiobooks_title'), 'audiobooks', ['title'], unique=False)
    op.create_index(op.f('ix_audiobooks_visibility'), 'audiobooks', ['visibility'], unique=False)
    op.create_table('chapters',
    sa.Column('audiobook_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('audio_url', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audiobook_id'], ['audiobooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapters_audiobook_id'), 'chapters', ['audiobook_id'], unique=False)
    op.create_index(op.f('ix_chapters_id'), 'chapters', ['id'], unique=False)
    op.create_table('generation_jobs',
    sa.Column('audiobook_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='audiobookstatus', native_enum=False), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['audiobook_id'], ['audiobooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_jobs_audiobook_id'), 'generation_jobs', ['audiobook_id'], unique=False)
    op.create_index(op.f('ix_generation_jobs_id'), 'generation_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_generation_jobs_status'), 'generation_jobs', ['status'], unique=False)
    op.create_table('library',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('audiobook_id', sa.Uuid(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['audiobook_id'], ['audiobooks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'audiobook_id', name='uq_user_audiobook_library')
    )
    op.create_index(op.f('ix_library_audiobook_id'), 'library', ['audiobook_id'], unique=False)
    op.create_index(op.f('ix_library_id'), 'library', ['id'], unique=False)
    op.create_index(op.f('ix_library_user_id'), 'library', ['user_id'], unique=False)
    op.create_table('playback_progress',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('audiobook_id', sa.Uuid(), nullable=False),
    sa.Column('chapter_id', sa.Uuid(), nullable=True),
    sa.Column('position_seconds', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['audiobook_id'], ['audiobooks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'audiobook_id', name='uq_user_audiobook_playback')
    )
    op.create_index(op.f('ix_playback_progress_audiobook_id'), 'playback_progress', ['audiobook_id'], unique=False)
    op.create_index(op.f('ix_playback_progress_chapter_id'), 'playback_progress', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_playback_progress_id'), 'playback_progress', ['id'], unique=False)
    op.create_index(op.f('ix_playback_progress_user_id'), 'playback_progress', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_playback_progress_user_id'), table_name='playback_progress')
    op.drop_index(op.f('ix_playback_progress_id'), table_name='playback_progress')
    op.drop_index(op.f('ix_playback_progress_chapter_id'), table_name='playback_progress')
    op.drop_index(op.f('ix_playback_progress_audiobook_id'), table_name='playback_progress')
    op.drop_table('playback_progress')
    op.drop_index(op.f('ix_library_user_id'), table_name='library')
    op.drop_index(op.f('ix_library_id'), table_name='library')
    op.drop_index(op.f('ix_library_audiobook_id'), table_name='library')
    op.drop_table('library')
    op.drop_index(op.f('ix_generation_jobs_status'), table_name='generation_jobs')
    op.drop_index(op.f('ix_generation_jobs_id'), table_name='generation_jobs')
    op.drop_index(op.f('ix_generation_jobs_audiobook_id'), table_name='generation_jobs')
    op.drop_table('generation_jobs')
    op.drop_index(op.f('ix_chapters_id'), table_name='chapters')
    op.drop_index(op.f('ix_chapters_audiobook_id'), table_name='chapters')
    op.drop_table('chapters')
    op.drop_index(op.f('ix_audiobooks_visibility'), table_name='audiobooks')
    op.drop_index(op.f('ix_audiobooks_title'), table_name='audiobooks')
    op.drop_index(op.f('ix_audiobooks_status'), table_name='audiobooks')
    op.drop_index(op.f('ix_audiobooks_owner_id'), table_name='audiobooks')
    op.drop_index(op.f('ix_audiobooks_language'), table_name='audiobooks')
    op.drop_index(op.f('ix_audiobooks_id'), table_name='audiobooks')
    op.drop_index(op.f('ix_audiobooks_author'), table_name='audiobooks')
    op.drop_table('audiobooks')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
