"""add audio_url and duration_seconds

Revision ID: b2605401c231
Revises: a4d7c2e3b56f
Create Date: 2026-10-05 18:39:48.573450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2605401c231'
down_revision: Union[str, Sequence[str], None] = 'a4d7c2e3b56f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audiobooks', sa.Column('audio_url', sa.String(length=1024), nullable=True))
    op.add_column('audiobooks', sa.Column('duration_seconds', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audiobooks', 'duration_seconds')
    op.drop_column('audiobooks', 'audio_url')
    # ### end Alembic commands ###
